name: Create Project

on:
  push:

jobs:
  create:
    name: Create Project
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: github.repository != 'jeswr/template-typescript'
    steps:
      - uses: actions/checkout@v4
      - run: npx zx instantiate.mjs
      - run: |
          git config --global user.name 'Jesse Wright'
          git config --global user.email '63333554+jeswr@users.noreply.github.com'
          git add .
          git commit -am "chore: automatically instantiate" -n
          git push --set-upstream origin main
    env:
      GH_TOKEN: ${{ github.token }}
